### ISSUE TITLE
Remove TF dependency

### ISSUE THREAD

**Issue by evgenii-nikishin** [ikostrikov/jax-sac#1]
TF is a heavy library that might need a lot of dependencies and time to install. Removing the dependency on tensorflow_probability is not essential but might be good too.

**Comment by ikostrikov** [comment]
Sounds good to me! Feel free to submit a PR.

**Comment by ikostrikov** [comment]
I would prefer to keep tensorflow_probability since it might easier to add flow policies, etc..

**Comment by evgenii-nikishin** [comment]
Fixed in #8
