### ISSUE TITLE
Discount factor in main.py might be misleading

### ISSUE THREAD

**Issue by evgenii-nikishin** [ikostrikov/jax-sac#3]
Right now it indicates whether the env is done due to a timelimit, while in the update we use 0.99.

**Comment by ikostrikov** [comment]
Yes, I think it's worth renaming it into mask.

**Comment by ikostrikov** [comment]
Fixed in https://github.com/ikostrikov/jax-sac/commit/4789c28e14d870132bd111eee44e4270d369d6e1
